//@version=4
// Made by TPCharts (twitter.com/tradeprophet). Modify as you like, and follow on Twitter for more free goodies!
study(title="Chad's Alert EMAs (@tradeprophet)", overlay=true)

// Maybe you like looking at daily EMA's on a 4-hour chart, you twisted bastard.
//timeframe = input(title="EMA timeframe (e.g. 'D' shows daily EMAs on 4h chart)", type=input.resolution, defval="D")
timeframe =""

// EMA lengths
emaShorterLength = input(title="Shorter EMA's length", type=input.integer, defval=9)
emaLongerLength = input(title="Longer EMA's length", type=input.integer, defval=18)

// Shorter EMA Aesthetics
emaShorterTransparency = input(title="Shorter EMA's Transparency", type=input.integer, defval=80)
emaShorterWidth = input(title="Shorter EMA's Width", type=input.integer, defval=1)

// Longer EMA Aesthetics
emaLongerTransparency = input(title="Longer EMA's Transparency", type=input.integer, defval=60)
emaLongerWidth = input(title="Longer EMA's Width", type=input.integer, defval=1)

// Calculate the EMAs
emaShorterClose = ema(security(syminfo.tickerid, timeframe, close), emaShorterLength)
emaLongerClose = ema(security(syminfo.tickerid, timeframe, close), emaLongerLength) 

isCrossover = cross(emaShorterClose, emaLongerClose)
alertcondition(isCrossover, title="Chad's EMA Crossed", message="{{exchange}}:{{ticker}}'s {{\"emaShorterLength\"}}/{{\"emaLongerLength\"}} EMAs crossed")

// Plot them
plot(series=emaShorterClose, color=color.black, linewidth=emaShorterWidth, transp=emaShorterTransparency)
plot(series=emaLongerClose, color=color.black, linewidth=emaLongerWidth, transp=emaLongerTransparency)