//@version=2

// Had to use V2 of Pinescript for this, there are some odd quirks with open/close prices in v3. Not really sure what's going on there.

study(title="Chad's ADR (@tradeprophet)", overlay=true)

length = input(defval=5, title="Length", type=integer, minval=1)
offset = input(defval=0, title="Offset", type=integer, minval=0)
use_av = input(defval="EMA", title="EMA/SMA", type=string)
today_only = input(defval=false, title="Show Today Only", type=bool)

// Used to calculate true range
high0 = security(tickerid, 'D', high[offset])
low0 = security(tickerid, 'D', low[offset])
close1 = security(tickerid, 'D', close[1 + offset])
open0 = security(tickerid, 'D', open) 

datr = max(max(high0 - low0, abs(high0 - close1)), abs(low0 - close1))
smooth = security(tickerid, 'D', use_av=="SMA" ? sma(datr, length) : ema(datr, length))

milliseconds_in_1day = 1000 * 60 * 60 * 24 * 1
midnight_today = timenow - (timenow % milliseconds_in_1day)

leftborder = time >= midnight_today or (not today_only)
rightborder = false //barstate.isrealtime

p1 = plot(open0 + smooth, color=leftborder and not rightborder ? black : na, title='Upper ADR', linewidth=1, style=cross)
p2 = plot(open0 - smooth, color=leftborder and not rightborder ? black : na, title='Lower ADR', linewidth=1, style=cross)

// I wonder if 'NeoButane' will steal this script too! lol dickhead.

