//
// START TPCharts Utils
//
toPips(v) => syminfo.type == 'forex' ? v/syminfo.mintick/10 : v

getPrice(condition, ohlc) => 
    float ret = na
    if condition and na(ret[1])
        if ohlc == "o"
            ret := open
    else
        ret := ret[1]
    ret[0]

uVal(interval, amount) => 
    iDay = 86400000
    iWeek = iDay * 6 // Assuming Sunday not included in chart
    iHour = iDay / 24
    iMinute = iHour / 60

    multiplier = 0

    if interval=="W"
        multiplier := iWeek

    if interval=="D"
        multiplier := iDay
    
    if interval=="60"
        multiplier := iHour

    multiplier * amount

drawLine(price, timeStart, timeEnd) => 
    line.new(x1=timeStart, y1=price, x2=timeEnd, y2=price, extend=extend.none, xloc=xloc.bar_time, color=color.new(color.black, 50))

drawLineLabelAlign(line, text, alignment) =>
    align = timenow

    if alignment == "l"
        align := line.get_x1(line)

    if alignment == "r"
        align := line.get_x2(line)

    if alignment == "c"
        align := timenow < line.get_x2(line) ? timenow+uVal("60", 1) : line.get_x2(line)+uVal("60", 1)

    label.new(align, line.get_y1(line), text, style=label.style_none, color=color.black, xloc=xloc.bar_time, size=size.small)

drawLineLabel(line, text) => drawLineLabelAlign(line, text, "r")

getSValText(condition, text, value) => condition ? text + " (" + value + ")" : text

getValText(condition, text, value) => getSValText(condition, text, tostring(value))

//
//END TPCharts Utils
//